spring:
  data:
    mongodb:
      username: zouliga
      password: zouliga
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
