server:
  port: 8070

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/order
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderConfirmation:com.zouliga.kafka.OrderConfirmation


#application:
#  config:
#    customer-url: http://localhost:8222/api/v1/customers
#    product-url: http://localhost:8222/api/v1/products
#    payment-url: http://localhost:8222/api/v1/payments
#    connect directly to the service if not using api gateway. No scalability
#    customer-url: http://localhost:8090/api/v1/customers
#    product-url: http://localhost:8050/api/v1/products
#    payment-url: http://localhost:8060/api/v1/payments