spring:
  config:
    import: configserver:http://config-server:8888
  application:
    name: discovery-service

eureka:
  instance:
    prefer-ip-address: true
    hostname: discovery-service
  client:
    service-url:
      defaultZone: "http://discovery-service:8761/eureka/"

server:
  port: 8761