
#spring:
#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
spring:
  config:
    use-legacy-processing: true

server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: false # don't register this service in eureka server
    fetch-registry: false