
spring:
  application:
    name: discovery-service
  config:
    use-legacy-processing: true


server:
  port: 8761

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false
