
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: order-service

application:
  config:
    customer-url: http://localhost:8222/api/v1/customers
    product-url: http://localhost:8222/api/v1/products
    payment-url: http://localhost:8222/api/v1/payments